version: '3.7'
services:
  db:
    image: mysql:${MYSQL_VERSION:-latest}
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mpp_dev}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./persistent:/var/lib/mysql
    ports:
      - '${MYSQL_PORT:-3306}:3306'
      - '${MYSQL_PORT_RESERV:-33060}:33060'
    networks:
      - spring_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - '${PHPMYADMIN_PORT:-80}:80'
    environment:
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    depends_on:
      - db

  web:
    build: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-opana}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mpp_dev}
    ports:
      - ${WEB_PORT:-8080}:${WEB_PORT:-8080}
    command: mvn clean spring-boot:run
    depends_on:
      - db
    networks:
      - spring_net

volumes:
  persistent:

networks:
  spring_net:
